# Generated by Django 2.0.6 on 2018-06-02 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'ordering': ('makes', 'item'),
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=80)),
                ('batch_size', models.SmallIntegerField(default=1)),
                ('ingredients', models.ManyToManyField(through='minecraft.Ingredient', to='minecraft.Item')),
            ],
            options={
                'verbose_name': 'Item',
                'ordering': ('name',),
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makes', to='minecraft.Item'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='makes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minecraft.Item'),
        ),
    ]
